# theme = ""
disqusShortname = "athoscr"
languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "https://athoscr.me"
canonifyurls = true
title = "/home/athos"
author = "Athos Ribeiro"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[indexes]
category = "categories"
tag = "tags"
[Params]
AuthorName = "Athos"
github = "athos-ribeiro"
gitlab = "athos-ribeiro"
academic = "http://www.ime.usp.br/~athoscr"
# twitter = "senjindarshiva"
email = "athoscr@fedoraproject.org"
description = "Free Software, society and stuff"
# cv = "/pages/cv"
# legalnotice = "/pages/legal-notice"
# muut = "fredrikloch"
linkedin = "athos-ribeiro-521358114"
cover = "/images/zephyr_stickers.jpg"
# logo = "/img/logo-1.jpg"
[taxonomies]
    tag = "tags"
#[author]
    #name = "Athos Ribeiro"
