#!/bin/sh

REMOTE_SERVER="blog"
SITE_PATH="/var/www/blog"

if [ -d public ]
then
  echo 'Clean up'
  rm -rfI public
  git clean -xdf
fi

echo 'Compiling new content'
hugo

echo 'Pushing changes...'
rsync -avz --delete public/ $REMOTE_SERVER:$SITE_PATH

echo "done."
